### ISSUE TITLE
カテゴリの設定（seeds.rb の実装）

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#10]
#7 で作成してもらったカテゴリを seeds.rb で設定していく。
#8 のマージ後対応が必要。

1. #8 の対応でできた `public/categories.csv` というファイルに内容を書き込む
2. `rails db:seed` を実行し、categories テーブルに値が入るか確認

カテゴリの内容
https://drive.google.com/open?id=1xXGYZKx8wRugwz88U318eCGMg_MbAyW6

参考：データ投入は rails の seed 機能を用いて行う。
https://www.rubylife.jp/rails/model/index10.html

**Comment by hiracky16** [comment]
@Kuratech5 
Rails のエラー画面が出る？
エラーとかで調べると解決策が出てくるかも

**Comment by Kuratech5** [comment]
@hiracky16 
エラー内容
　Mysql2::Error::ConnectionError: Unknown MySQL server host 'db' (0)

今調べてるけど、まだわからない。

**Comment by Kuratech5** [comment]
解決
✗　rake db:seed 
○　docker-compose run web rake db:seed

ただそれだけでした。すみません。
