### ISSUE TITLE
User テーブルにユーザ情報を追加

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#11]
現状メールアドレスとパスワードしかないため他のカラムを追加する

User テーブル
https://docs.google.com/spreadsheets/d/1DU-n4gZ3pKss0nShDCFwOq00Hl2TDKYgQL68LSy44Po/edit#gid=1524240198&range=A1

**Comment by hiracky16** [comment]
@Kuratech5 
これお願い！

**Comment by hiracky16** [comment]
参考
https://qiita.com/azusanakano/items/a2847e4e582b9a627e3a#%E3%82%AB%E3%83%A9%E3%83%A0%E8%BF%BD%E5%8A%A0

**Comment by Kuratech5** [comment]
@hiracky16 
このコマンド入力して、テーブルにカラムが追加されることを確認しました。
この結果をどうやって開きに確認してもらえばいいですか？
docker-compose run web rails generate migration AddDetailsToUsers description:string type:integer image:integer

**Comment by hiracky16** [comment]
@Kuratech5 
多分そのコマンドだけじゃなかったはず、`docker-compose run web rails db:migrate` もやったはず
このコマンドは↑で作ったマイグレートファイルの内容を実行するコマンドです。
マイグレートは Rails プロジェクトにおけるテーブル操作を残しておくための仕組みです。
なんでマイグレートファイルさえあれば俺も確認できる。

**Comment by hiracky16** [comment]
これ一旦終わったのでクローズします。
