### ISSUE TITLE
seed を複数回実行すると 2 重でレコードが追加される

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#16]
categories テーブルに seed でレコードを追加するとすでに入っていたレコードが残ったままであった。
seed を実行する前にすでに入っているレコードを削除する対応が必要。

**Comment by Kuratech5** [comment]
@hiracky16 
おれがサーバ起動したままcommitしたから、残ってたのかも。
そうだね、seed実行前にその処理があればいいね！

**Comment by kento423** [comment]
@hiracky16 
レコードを初期化するコードを追加すればいいてこと？

**Comment by hiracky16** [comment]
@kento423 
初期化というより一旦すべて削除してから入れ直すとするとできる

**Comment by kento423** [comment]
@hiracky16 
categories, majorsについて、
レコードの前にdelete_allすることで対処しました。
あと、idも更新されるようになっています。
確認よろしく。

**Comment by hiracky16** [comment]
@kento423 確認しました〜
複数回実行しても都度レコードが追加されませんでした
また Id の インクリメントもありがとうございます！（自分は考慮不足でした…）
