### ISSUE TITLE
研究室(labs)テーブルからいらないカラムを削除

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#18]
画像登録のために用意していたが、ActiveStorage を使っており、要らなくなったので消す。

- main_image
- sub_image

マイグレーションを作ってから行う

**Comment by hiracky16** [comment]
@kento423 こちら進捗どうでしょう？

**Comment by kento423** [comment]
@hiracky16 ごめん、忙しくててつけれてなかった。
上の説明だけだと何をすればいいのかわからない状態 🆘

**Comment by hiracky16** [comment]
@kento423 やってることは↓と同じ。
https://github.com/premier-spa/research_app/issues/22
くらっちが対応してるのでわからなかった聞いてー
あと「rails カラム削除」などで調べてみるのもよいと思う。

**Comment by kento423** [comment]
@hiracky16 schemaとマイグレーションファイル2つaddしようとしてるんだけど、ファイルごと`git add db`としても良い？

**Comment by Kuratech5** [comment]
@kento423 いいとおもう
