### ISSUE TITLE
研究室検索機能の作成（学生用）

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#20]
学生が研究室を検索するための機能を `/search/lab` に作成する

**Comment by hiracky16** [comment]
当初 `search/lab` に作る予定でしたが、研究室一覧ページが `/labs` に会ったため、ここに検索機能を付け加える形にしました。

**Comment by hiracky16** [comment]
現状、検索エンジンとして ElasticSearch （以下 ES）を導入しようと試みています。
ES 自体は docker に導入できましたが、elasticsearch-rails という Rails から ES を叩くための gem が動作しないので少し悪戦苦闘しています。。
ES 導入の理由は SQL ベースの検索はとても遅いため今後の可用性のためと OSS で無料であるためです。

**Comment by Kuratech5** [comment]
@hiracky16 
いいね！ES興味あったから、嬉しいです！
特に異論は無いです。
よろしくお願いいたします！

**Comment by hiracky16** [comment]
https://github.com/elastic/elasticsearch-rails/issues/851
とりあえず公式の方に issue を立てて様子見ます。
長く掛かりそうなら別の方法を考えます。

**Comment by Kuratech5** [comment]
残りタスクは新issueにあるのでこちら閉じますね
