### ISSUE TITLE
ユーザ(users)からいらないカラムを削除

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#22]
image を削除する
active storage で実装したので必要なくなった

**Comment by hiracky16** [comment]
image を削除する

**Comment by Kuratech5** [comment]
@hiracky16 
申し訳ない。記載し忘れていたけど、ちゃんとマイグレーションスクリプト書いて、削除したはず。

**Comment by hiracky16** [comment]
@Kuratech5 
https://github.com/premier-spa/research_app/pull/21/files#diff-1acd2e7e27a227829d5d14a91c863bb6L102
スキーマ上消えてるけどマイグレートファイルが add されていないみたいですね…
見落としていて申し訳ないですが、このイシューでそのマイグレートファイルを add してください。
