### ISSUE TITLE
学生のプロフィール機能

### ISSUE THREAD

**Issue by Kuratech5** [premier-spa/research_app#29]
学生のプロフィール画面を充実させる。

**Comment by hiracky16** [comment]
@Kuratech5 
これ対応します。
一旦学生だけやって、できそうなら教授の方も学生を参考にしながら、
他の人にやってもらいたいと考えています。

**Comment by Kuratech5** [comment]
@hiracky16 
助かります。お願いします。

**Comment by hiracky16** [comment]
面白い記事発見
https://qiita.com/kidach1/items/789c2e7aebbcfbd2583e
おそらくやろうとしていることは一緒なので参考にしながらやってみる。

**Comment by hiracky16** [comment]
@Kuratech5 
現状 User クラス（users テーブル）を親クラスにして教授クラス Professor と学生クラス Student をそれぞれ作ろうと考えています。
User には教授と学生に共通する情報をもたせて、固有の情報をそれぞれに持たせる想定です。
それぞれのテーブル（professors と students）も作成します。

その際にどのように情報をもたせたらいいかちょっとわからなくなってしまったのでテーブル設計の見直しをお願いしてもいいですか？

共通の情報を users に それぞれに持たせる情報を professors, students のシートに記入していただけると嬉しいです。
https://docs.google.com/spreadsheets/d/1DU-n4gZ3pKss0nShDCFwOq00Hl2TDKYgQL68LSy44Po/edit#gid=1524240198

**Comment by Kuratech5** [comment]
@hiracky16 
ありがとうございます！記事も確認したので、大体どういうことをやろうかしているのは理解できました。
シートに書いておきますね！

**Comment by Kuratech5** [comment]
@hiracky16 
テーブル定義修正しました。詰める必要があると思いますが、ひとまずこれで！

**Comment by hiracky16** [comment]
@Kuratech5 ありがとうございます！
情報に関して確認取れました！
ただ、テーブル設計に関して思うところがあったのでシートの方にコメントしました。
ご確認よろしくおねがいします。

**Comment by hiracky16** [comment]
追加タスク
- User テーブルに学歴 academic_career のカラムを追加
- students テーブルの希望業種と職種、勤務地、企業選びのポイント情報を追加

**Comment by Kuratech5** [comment]
STI実装完了したので閉じます
