### ISSUE TITLE
専攻(majar)の選択

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#34]
labs テーブルに専攻を表す majar がありフリーテキストで入力する形であるが、これを選択式に変更する
それにあたって majar すべてを保持するテーブル (majars) を作りたい。
目的としては研究室検索時に選択項目として追加したいからである。

やることとしては以下が挙げられる。

- 専攻の洗い出し
- majars テーブルの用意（マイグレーションファイルの作成）
- seeds の編集

**Comment by Kuratech5** [comment]
@hiracky16 
了解です！
データを用意するほうが良いと思うので、指示通りで行きましょう。

**Comment by Kuratech5** [comment]
@今対応中です。
今週末にはデータ全部揃います。

**Comment by Kuratech5** [comment]
全国の大学・大学院に関する以下の情報が得られる予定。
大学サイトURL,学校区分,  所在地, 電話番号, 学部・研究科 専攻名・学科, 履修課程, 専門職大学

**Comment by Kuratech5** [comment]
@hiracky16 
テーブル定義書いてみました。長さはどう設定したらいいかわからなかったので空白です。
こんな漢字でしょうか？
https://docs.google.com/spreadsheets/d/1DU-n4gZ3pKss0nShDCFwOq00Hl2TDKYgQL68LSy44Po/edit#gid=1237218137

**Comment by hiracky16** [comment]
@Kuratech5 
こちら確認が遅くなってました…
大丈夫だと思います！
テーブル間の連携は都道府県と市町村のテーブルのマイグレーションファイルを参考にするとわかると思います。
またわからないことがあれば聞いてください。

**Comment by Kuratech5** [comment]
マージされたので閉じます
