### ISSUE TITLE
フロント各種ページの基礎を実装

### ISSUE THREAD

**Issue by Kuratech5** [premier-spa/research_app#35]
デザインのプロトタイプを元に、フロントの骨組みをつくる。
きれいなデザインは不要で、位置や要素がわかる程度のもの。

**Comment by hiracky16** [comment]
メモ
https://materializecss.com/getting-started.html
CSS のフレームワークを使って効率よく開発していく。

**Comment by Kuratech5** [comment]
いろいろといじってみましたが、データを表示するにあたり考慮すべきことがいくつかあるので、現状の機能に対しデザインをあてるだけにします。カード内の画像がなぜか読み込めない。

**Comment by Kuratech5** [comment]
@hiracky16 
結構変わってるはずなので、確認してみてください。
こんな感じでよければガンガン枠組みを実装していきます。
データを引っ張ってくるところとかはいろいろ考慮しないといけないことありそうなので、とりあえずダミーデータで対処していきます。

**Comment by hiracky16** [comment]
@Kuratech5 
確認しました！
めっちゃいい感じに再現できてるね！
こんな感じ大丈夫だと思います！

**Comment by Kuratech5** [comment]
> いろいろといじってみましたが、データを表示するにあたり考慮すべきことがいくつかあるので、現状の機能に対しデザインをあてるだけにします。カード内の画像がなぜか読み込めない。

ダミーデータを利用していて、画像の置き場所をpublic配下にしていた。パスの指定が少し特殊であり、それが間違っていただけでした。
