### ISSUE TITLE
User モデルの has_labs の修正

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#43]
現状動いていない模様。
https://github.com/premier-spa/research_app/blob/master/app/models/user.rb#L20
ここの配列の長さをチェックするようにすればよいと思われる。
`.empty?` メソッドを使用すればできると思われる。
https://qiita.com/somewhatgood@github/items/b74107480ee3821784e6

**Comment by hiracky16** [comment]
@kento423 
いま持ってるイシューが終わったらこちらもお願いします。

**Comment by Kuratech5** [comment]
@domi10momo 
こちら対応お願いします

**Comment by domi10momo** [comment]
has_labs[0]に値が入ってたらreturn trueってことでOK?
質問としては、このhas_labsの値をどこで使ってるのかが分からない・・・
layout/apprication.html.erb24行目に代用の応急処置が書いてあるのは見つけたけど

**Comment by hiracky16** [comment]
全部ボタンにしなくていいよ
デザイン変わるのは仕方ないから削除さえ出来ればよいということで
デザイン修正のイシューをつくってもらえると助かる

**Comment by hiracky16** [comment]
上にも書いてますがempty?メソッドを使ってください。
使用箇所はすぐにはわかりませんが、文字列検索すればわかるはずです。
