### ISSUE TITLE
フロント実装（検索画面）

### ISSUE THREAD

**Issue by Kuratech5** [premier-spa/research_app#46]
項目：編集ファイル
検索・結果表示：research_app/app/views/labs/index.html.erb

デザインプロトタイプを参考に検索画面のフロント実装をお願いします。

【参考URL】
・グリッド：https://materializecss.com/grid.html
・ボタン：https://materializecss.com/buttons.html
・カード:  https://materializecss.com/cards.html
・アイコン：https://materializecss.com/icons.html
・画像：https://materializecss.com/media.html
・テキストインプット：https://materializecss.com/text-inputs.html
・チェックボックス：https://materializecss.com/checkboxes.html
・Collapsiible：https://materializecss.com/collapsible.html
・ページネーション：https://materializecss.com/pagination.html
・サーチバー：https://materializecss.com/navbar.html
※Search Barというものが用意してあります。
※条件指定はcollapsible内にチャックボックスを配置すると良い感じになるのではないかと思っています。

【参考ファイル】
works/index.html.erb
カード内のデザインはこれが参考になると思います。

**Comment by hiracky16** [comment]
@Kuratech5 
指示書ありがとうございます！
これだけ書いてあったら自分もできそう

**Comment by hiracky16** [comment]
tip : kaminari のデザイン変更
https://qiita.com/you8/items/f10c62f3faa9974932d4

**Comment by hiracky16** [comment]
マージされたので完了！
