### ISSUE TITLE
フロントの実装（Contact us）

### ISSUE THREAD

**Issue by Kuratech5** [premier-spa/research_app#47]
項目：編集ファイル
Contact usの表示：research_app/app/views/labs/contact.html.erb

デザインプロトタイプを参考にContact us画面のフロント実装をお願いします。
【参考URL】
・グリッド：https://materializecss.com/grid.html
・ボタン：https://materializecss.com/buttons.html
・カード: https://materializecss.com/cards.html
・アイコン：https://materializecss.com/icons.html
・画像：https://materializecss.com/media.html

**Comment by Kuratech5** [comment]
@hiracky16 
マップが入るところなので、お願いします。

**Comment by hiracky16** [comment]
マージされたんでこちらクローズします。
