### ISSUE TITLE
フロント実装（Photos）

### ISSUE THREAD

**Issue by Kuratech5** [premier-spa/research_app#49]
項目：編集ファイル
表示画面：research_app/app/views/albums/index.html.erb
編集画面：research_app/app/views/albums/edit.html.erb
登録画面：research_app/app/views/albums/new.html.erb
テンプレ：_form.html.erb

デザインプロトタイプを参考にPhotos画面のフロント実装をお願いします。
現在、アルバムの年度を指定するところまでは実装しているので、その中身の実装をお願いします。
参考例として既に要素が配置してありますが、何を使うかは任せます。

【参考URL】
・グリッド：https://materializecss.com/grid.html
・ボタン：https://materializecss.com/buttons.html
・カード: https://materializecss.com/cards.html
・色：https://materializecss.com/color.html
・アイコン：https://materializecss.com/icons.html
・画像：https://materializecss.com/media.html
・タブ：https://materializecss.com/tabs.html
・テキストインプット：https://materializecss.com/text-inputs.html

【参考ファイル】
research_app/app/views/device/registrations/new.html.erb
編集・登録画面はこれが参考になると思います。
※ここのデザインはあとで要改善なので、同様のものをつくるだけでいいです。

**Comment by Kuratech5** [comment]
@kento423
feature/design_headerがマージされ次第、対応お願いします。

CSSファイルは特に用意していません。
HTML参考：https://html-coding.co.jp/annex/dictionary/html/
CSS参考：https://developer.mozilla.org/ja/docs/Web/CSS

テキスト色などは↓にまとめてあります。わかりにくい場合、メッセください。
https://docs.google.com/spreadsheets/d/1VlLW8zTTQ3F7rzgLZl9kLfc-jNBuICHePtM5QWIcmIs/edit#gid=2090274330

**Comment by Kuratech5** [comment]
@kento423 
こちら引き取ります。

**Comment by hiracky16** [comment]
@Kuratech5 
こちらマージしました。
Rails への組み込みも終わってるっぽいのでクローズ。

※ 時間があったら対応
- view 側にあるロジックをコントローラに移せないか検討
