### ISSUE TITLE
研究室ページのプロトタイプ作成

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#5]
[プロトタイプ案 version 1.0](https://xd.adobe.com/view/f0c89bae-78b1-44e6-7cd0-4a322e20e8d2-86f9/)
最低限載せるべき情報は↑を参考にし、デザイン + プロトタイプを作成する。
プロトタイプは Xd か他のツールで作る。

**Comment by hiracky16** [comment]
@morinokumakamesan デザインの作成お願いします。
まずは画像ベースで作ってから他の人達のレビュー入れてプロトタイプの作成に入るって感じにしましょう。

@Kuratech5 サポートお願いします！

**Comment by Kuratech5** [comment]
＠hiracky16
了解です。

@morinokumakamesan 
草案はSlackで以前、直接送ったやつです。確認お願いします。
ページ要素以外のデザイン面はある程度自由にしてくれて大丈夫です。

**Comment by Kuratech5** [comment]
プロトタイプのデザインは終わっているので閉じます。
追加で実装する際に、デザインissuをつくって貰えればと思います。
