### ISSUE TITLE
ログアウトができない

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#52]
`users/sign_out` が No route エラーになる。
原因調査からやる。

**Comment by Kuratech5** [comment]
このバグ未だに残ってる？？

おれがエラーになったときは、jsの読み込みあたりが、原因だったぽいけど・・・

**Comment by hiracky16** [comment]
`<%= link_to destroy_user_session_path %>` → `<%= button_to destroy_user_session_path %>` に変更

**Comment by Kuratech5** [comment]
マージしたので閉じますね！
