### ISSUE TITLE
メニューバー内のリンクパス修正

### ISSUE THREAD

**Issue by Kuratech5** [premier-spa/research_app#56]
現状では、ログインユーザに基づいたルーティングになっている。
そのため、メニューバーを利用したサイト内の画面遷移を行おうとすると、必ず自分の研究室HPにとんでしまう。

これを、任意のユーザが任意の研究室サイトページを閲覧できるように修正する。

例：
```
labs/:lab_id/works/:id
labs/:lab_id/people/:id
```

idパラメータは、メニューバー内にMyLaboratoryへ飛ぶボタンを作成したいのでできればほしい。
ユーザのログイン状態が確認できるのであれば、パスにid paramを含めなくてもよいが、そこあたりの詳細の知識がないので分かる方いたら教えてください。

おそらく
routes.rb内の
member doを削除して、
```
get 'about'
get 'people'
get 'contact'
```
もしくは
```
get '/about/:id', to: 'labs#about', as: 'about'
get 'people/:id', to: 'labs#people', as: 'people'
get 'contact/:id', to: 'labs#contact', as: 'contact'
```
のようにすればよいのではないかと思っている。
もっとスマートな書き方があったらすみません。

そして、labs_controller.rb内で
それぞれのアクションを設定し直す必要があるのではないかと思ってます。

```
    def set_lab
      @lab = Lab.find(params[:id])
    end
```
↓かな??? lab_idさえ決まれば、一意に研究室は決まるはずである。edit, update, destroyに関してはauthenticate_lab_user?が設定されているので、ここでidを利用する必要はないのでは？？
```
    def set_lab
      @lab = Lab.find(params[:lab_id])
    end
```

```
    # lab に紐づくニュース一覧を取得
    def set_news
      @news = News.where(lab_id: params[:id])
    end
```
↓params[:id]だと、自分のニュースしか取得できなさそうだけど、どうでしょうか？？
```
    # lab に紐づくニュース一覧を取得
    def set_news
      @news = News.where(lab_id: params[:lab_id])
    end
```

```
    # lab に紐づくアルバム一覧を取得
    def set_albums
      @albums = Album.where(lab_id: params[:id])
    end
```
↓ニュースと同様
```
    # lab に紐づくアルバム一覧を取得
    def set_albums
      @albums = Album.where(lab_id: params[:lab_id])
    end
```

```
    # lab に紐づく研究内容一覧を取得
    def set_works
      @works = Work.where(lab_id: params[:id])
    end
```
↓ニュースと同様
```
    # lab に紐づく研究内容一覧を取得
    def set_works
      @works = Work.where(lab_id: params[:lab_id])
    end
```

**Comment by hiracky16** [comment]
@Kuratech5 
> そのため、メニューバーを利用したサイト内の画面遷移を行おうとすると、必ず自分の研究室HPにとんでしまう。

メニューバーのリンクが current_user から取るようになってるからではないですか…？
https://github.com/premier-spa/research_app/blob/master/app/views/layouts/application.html.erb#L42

**Comment by Kuratech5** [comment]
@hiracky16 
うん、それはごもっともなんだが、
おれが理解できていないのか、ルーティングのところがしっくりこないんだよね〜
ちょっと新しくブランチ切ってやってみます

**Comment by hiracky16** [comment]
@Kuratech5 
ルーティングに問題があると判断している意味がよくわかりませんが、
変更する分にはもんだいありません。
ただ、RESTful な作りにしてほしいです。
FYI: https://railsguides.jp/routing.html

**Comment by Kuratech5** [comment]
@hiracky16 
すみません、おれの理解不足でした。
大丈夫そうです。

**Comment by Kuratech5** [comment]
@hiracky16 
マージされたのでcloseします
