### ISSUE TITLE
研究室所属申請機能（From 学生 to 教授）をつくる

### ISSUE THREAD

**Issue by Kuratech5** [premier-spa/research_app#57]
学生が研究室に所属するための登録申請（もしくは招待機能）機能をつくる

【制約】
学生は研究室サイトを作成できない。
教授のみが研究室サイトを作成できる。

・申請登録によって
学生と研究室間の関連テーブル？（lab_users）を更新すればよいのではないかと思っている。
見当違いだったらすみません。

※招待形式であれ、申請形式であれ結果的に得たい状態（テーブル関係の更新）は共通であるはず。

**Comment by Kuratech5** [comment]
@hiracky16 
これの優先度、割と高めです。
ElasticSearchが落ち着いたあとで大丈夫なので対応してもらえると助かります。

**Comment by hiracky16** [comment]
@Kuratech5 
了解しました！
一旦自分の方で仕様を考えて見るのでできたらレビューお願いします。

**Comment by hiracky16** [comment]
別途資料は共有済み。

**Comment by hiracky16** [comment]
Action Mailer 周り
https://railsguides.jp/action_mailer_basics.html

**Comment by hiracky16** [comment]
こちらマージされたのでクローズ
