### ISSUE TITLE
研究室を削除できないバグを修正

### ISSUE THREAD

**Issue by Kuratech5** [premier-spa/research_app#60]
研究室を削除できるようにする。

app/views/labs/index.html.erb内の47行目
```
<%= link_to '削除', lab_path(lab), method: :delete, data: { confirm: 'Are you sure?' } %>
```

#52 と同様で
`<%= link_to  %>` → `<%= button_to  %>` に変更すればよい？

**Comment by domi10momo** [comment]
@Kuratech5 
了解です。ログアウト機能に引き続き確認します。

**Comment by domi10momo** [comment]
<img width="1440" alt="2018-10-26 10 55 11" src="https://user-images.githubusercontent.com/35606852/47540036-2054d480-d90e-11e8-8858-e55c68a7c12d.png">

button_to にしたらこのような表示になったけど特に問題ない？
削除一つだけがボタンになってるけど・・・

**Comment by domi10momo** [comment]
<img width="1440" alt="2018-10-26 11 02 54" src="https://user-images.githubusercontent.com/35606852/47540526-a1ad6680-d910-11e8-94c8-0ffbef06e619.png">

全部ボタンにしたら何か気持ち悪くなった・・・

**Comment by hiracky16** [comment]
全部ボタンにしなくていいよー
今回は削除さえ出来ればいいから、デザインは気にせずともよいです。
デザイン修正のイシューだけつくってもらえると助かる

**Comment by Kuratech5** [comment]
マージしたので閉じますね！
