### ISSUE TITLE
city にアソシエーションが書かれていない

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#61]
アソシエーションを書いていないため `city.prefecture` という記述ができない。
以下を参考に `app/models/city.rb` にアソシエーションを追加する。

参考:https://railsguides.jp/association_basics.html

**Comment by hiracky16** [comment]
現状使っていないため使うときに付け足す感じで〜

**Comment by Kuratech5** [comment]
@hiracky16 
確かに、majorとかつくるときに参考にしたけど、何もなかったから、それでも大丈夫なのかと思って、真似してた
major,course,universityにも記述しときます。

**Comment by hiracky16** [comment]
@Kuratech5 こっちに記述してなかったからだよね…
city 参考にしてと言って申し訳ないです…

**Comment by Kuratech5** [comment]
#90 で対応しました。閉じます。
