### ISSUE TITLE
newsのコントローラを閲覧中の研究室に紐づくように修正。

### ISSUE THREAD

**Issue by Kuratech5** [premier-spa/research_app#63]
WorkとNewsのコントローラにおいて
閲覧中の研究室サイトに紐づくコンテンツが紐づくように修正する。

現状では、どこの研究室サイトからでも、全てのWorkとNewsが表示されてしまっている。

**Comment by Kuratech5** [comment]
Workに関しては #100 で対応しました。

**Comment by domi10momo** [comment]
#100にてnewsも紐づき修正されているようです。イシュークローズしようと思います。
