### ISSUE TITLE
news を user ページから登録できるようにする

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#67]
現状どちらも lab に紐付いている。
研究内容や研究室に関するニュースは就職活動に役に立ちユーザ起因で投稿されるべきであるため紐づく先を変える。

やることは以下のことだと思われる。
- works と news テーブルの lab_id を削除（外部キー制約もこのとき消す）
- works と news に user_id を追加
- work.rb と news.rb のアソシエーションを user に変更
- 既存の works と news を使っているページを編集（user から取得するようにする）
- ユーザページに投稿画面を用意する

**Comment by Kuratech5** [comment]
worksはLabに紐付けるのでそのまま。

newsのみをuserに紐付ける。
#63にも関わる部分なので、同じ人が対応すると楽だと思われる。

ということで@domi10momo お願いします。

**Comment by hiracky16** [comment]
@domi10momo 
ヒモ付を変えることによって、ニュース登録ができなくなってしまうと思います。
また、研究室の news からニュース一覧が見れていたのが見れなくなったりと、紐付けを変えると弊害が結構あります。

今回それらも修正してほしいです。
ちょっと大変ですがよろしくお願いします。

@Kuratech5

**Comment by domi10momo** [comment]
@Kuratech5  @hiracky16 
lab, user, news の関連性が複雑なため、従来通りnewsはlabに紐づいて表示されるようにする。
ただ、newsにユーザの情報が現在無いため、newsにuser_idを追加する。

**Comment by domi10momo** [comment]
indexへnews登録ページへのリンク付け

**Comment by hiracky16** [comment]
完了！
お疲れ様でした。
@domi10momo @Kuratech5
