### ISSUE TITLE
works（研究内容）をユーザに紐づくようにする

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#68]
#67 と同じ内容。
研究内容もユーザ起因で登録されるようにする。

**Comment by Kuratech5** [comment]
@hiracky16 
publicationsに関してはユーザに紐づくようにしてOKだと思う！！
worksに関しては、ちょっとまって、
これらに関しては今度のMTGで設計方針を話し合いましょう！

**Comment by hiracky16** [comment]
@Kuratech5 works は違ったのか…
publications というのはテーブル名で言うところの news ？

**Comment by Kuratech5** [comment]
@hiracky16 
すまん、newsのことです！

**Comment by hiracky16** [comment]
対応しません、クローズ。
@Kuratech5
