### ISSUE TITLE
カテゴリの設定

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#7]
TOP ページのニュースに設定するカテゴリの一覧を洗い出す。

TOPページ
https://xd.adobe.com/view/f0c89bae-78b1-44e6-7cd0-4a322e20e8d2-86f9/

カテゴリは categories というテーブルで管理する。
データ投入は rails の seed 機能を用いて行う。

参考: https://www.rubylife.jp/rails/model/index10.html

**Comment by hiracky16** [comment]
@Kuratech5 
これお願い！
まずはカテゴリを csv かなにかで一覧にして上げといて
categories テーブルは予めこちらで作っておきます。

**Comment by Kuratech5** [comment]
To do
- [ ] カテゴリを調査
- [ ] csvファイルにまとめる
- [ ] Googleドライブで共有

**Comment by Kuratech5** [comment]
Newsのカテゴリー ver 1
https://drive.google.com/open?id=1xXGYZKx8wRugwz88U318eCGMg_MbAyW6

**Comment by Kuratech5** [comment]
@hiracky16 確認お願いします。
- [ ] 確認しました。

**Comment by hiracky16** [comment]
@Kuratech5 
カラムの名前をテーブル定義と同じにしてください。
https://docs.google.com/spreadsheets/d/1DU-n4gZ3pKss0nShDCFwOq00Hl2TDKYgQL68LSy44Po/edit#gid=1564110699&range=A1

あと日本語のカテゴリもほしいです…

**Comment by Kuratech5** [comment]
ごめん、指示の意味が理解できてない。
categoriesテーブル内のnameカラムとdescriptionカラム内に入る値を洗い出すのがissueではない？

**Comment by hiracky16** [comment]
@Kuratech5 
そうだよ
じゃあ for what が description という理解でいい？

**Comment by Kuratech5** [comment]
@hiracky16 
description内の値を日本語にするってことでOK？
それともNameも？

**Comment by Kuratech5** [comment]
カテゴリーテーブル内の値を作りました。
https://drive.google.com/open?id=1rHyDsAanX3FCsgn13XFfbwFQlaTX4elA
https://drive.google.com/open?id=10Gyesg631SQw0xve9Urrlww7UzoA5y54

確認お願いします。
説明は日本語でもいいけど、nameの表示は英語の方がかっこいいし、しっくりくる気がする。

**Comment by hiracky16** [comment]
@Kuratech5 
Rails には国際化の機能もあるのでこれで対応するのはどうでしょうか？
https://railsguides.jp/i18n.html

**Comment by Kuratech5** [comment]
@hiracky16 
日本語のページはnameもdescriptionも日本語にして、英語のページを国際化の昨日で対応するということ？？

**Comment by hiracky16** [comment]
@Kuratech5 
そう
ただ、すべてで英語でいいのならしなくてもよいけどね。

**Comment by Kuratech5** [comment]
英語verは必須だと思う。

ただ、おれが言いたかったのは、categoriesテーブルのname内の値は日本語verでも英語表記の方がいいんじゃないかってこと。
テーブル内の値をそのまま使うなら、英語の方がいいと思う。
descriptionは日本語でもいいけどね

**Comment by hiracky16** [comment]
@Kuratech5 
じゃあデフォルトは日本語にして、i18n 使って今後英語対応していくってことにしよう
英語化は変換用の辞書を用意するだけだからあとからでも対応可能だと思う
カテゴリの内容に関しては何も言うことないです！

**Comment by Kuratech5** [comment]
@hiracky16 
サンキュー。ナイス提案です！
良いgemが用意してあるもんだね。

**Comment by hiracky16** [comment]
@Kuratech5 
そうだね！
じゃあクローズします。
引き続き #10 対応お願いします！
