### ISSUE TITLE
products テーブルの作成

### ISSUE THREAD

**Issue by hiracky16** [premier-spa/research_app#70]
ユーザの成果物を管理する products テーブルを作成する。
products は user_id を持ち users に紐づくようにする。
テーブル設計から行う必要あり。

**Comment by hiracky16** [comment]
@Kuratech5 
一旦 products に必要そうなカラムの洗い出しお願いします！（table definision への記述）
products テーブルの作成は他の人にやってもらおうと考えています。

**Comment by Kuratech5** [comment]
@hiracky16 
洗い出しました〜

**Comment by hiracky16** [comment]
@Kuratech5 確認しました〜。
大丈夫だと思います！

@kento423 
こちらを優先して対応お願いします！

**Comment by kento423** [comment]
プロダクトてのは論文とかのことですか？
あと、nameがintegerになってるけどstringじゃなくてこのままでよろしいの？

**Comment by hiracky16** [comment]
@kento423 確認漏れてました…
@Kuratech5 修正お願いします。URL もたまに長いのとかあるから text のほうがいいかもです。

**Comment by Kuratech5** [comment]
@kento423 @hiracky16 
すみません、ミスです。
修正しました。

**Comment by hiracky16** [comment]
@kento423 残してていいよ
Rails（ActiveRecord） ではレコードの作成日時 `created_at` と更新日時 `updated_at` がデフォルトで入る仕様になってる

**Comment by Kuratech5** [comment]
@kento423 
ごめん、マージしてしまったけど、外部キー指定するとこの修正が必要だ
見落としてた^^;

**Comment by Kuratech5** [comment]
https://qiita.com/ryouzi/items/2682e7e8a86fd2b1ae47
https://qiita.com/publichtml/items/1fba15d8071fab66d043
こちら参考にして、

**Comment by Kuratech5** [comment]
https://qiita.com/ryouzi/items/2682e7e8a86fd2b1ae47
https://qiita.com/publichtml/items/1fba15d8071fab66d043
こちら参考にして、マイグレーションスクリプトのuser_idの部分を修正お願いします。

**Comment by Kuratech5** [comment]
修正も完了したので閉じますね
